apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: grafana.harville.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - grafana.harville.dev
          secretName: grafana-tls
