apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "9.0.0"
  values:
    admin:
      existingSecret: grafana-admin
    service:
      type: ClusterIP
      port: 3000
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/ingress.class: nginx
      tls:
        - hosts:
            - grafana.harville.dev
          secretName: harvilledev
      hosts:
        - host: grafana.harville.dev
          paths:
            - path: /
              pathType: Prefix
