apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "12.0.0"
  values:
    admin:
      existingSecret: grafana-secret
    service:
      type: ClusterIP
      port: 3000
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: grafana.harville.dev
          paths:
            - path: /
              pathType: Prefix

