apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: orion
  namespace: flux-system
spec:
  interval: 5m
  upgrade:
    force: true
  install:
    namespace: default
  chart:
    spec:
      chart: orion
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    gui:
      image:
        tag: 0.0.1   # {"$orion-image-tag":"orion-image-tag"}
    api:
      image:
        tag: 0.0.1   # {"$orion-image-tag":"orion-image-tag"}
