apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: orion
  namespace: flux-system

spec:
  interval: 5m
  targetNamespace: default
  upgrade:
    force: true
  chart:
    spec:
      chart: orion
      path: ./apps/orion
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    gui:
      image:
        tag: 0.0.1 # {"$orion-image-tag":"orion-image-tag"}
    api:
      image:
        tag: 0.0.1 # {"$orion-image-tag":"orion-image-tag"}
