apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vd
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/vd
      sourceRef:
        kind: GitRepository
        name: vd-charts
        namespace: flux-system
      interval: 1m
`
