apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vd
  namespace: default
spec:
  interval: 5m
  prune: true
  upgrade:
    force: true
  chart:
    spec:
      chart: ./charts/vd
      sourceRef:
        kind: GitRepository
        name: vd-charts
        namespace: flux-system
      interval: 1m
  values: # override so flux can update the image tag
    gui:
      image:
        tag: latest
    api:
      image:
        tag: latest
