apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vd
  namespace: default
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: ./charts/vd
      sourceRef:
        kind: GitRepository
        name: vd-charts
        namespace: flux-system
      interval: 1m
  values:
    gui:
      image:
        tag: 0.0.3   # {"$vd-image-tag":"vd-image-tag"}
      env:
        - name: VITE_API_URL
          value: "https://vd.harville.dev/api"
    api:
      image:
        tag: 0.0.3   # {"$vd-image-tag":"vd-image-tag"}
      env:
        - name: VITE_API_URL
          value: "https://vd.harville.dev/api"
        - name: DATABASE_URL
          value: postgresql://admin:password@vd-db:5432/vd_db
    db:
      image:
        tag: 0.0.3   # {"$vd-image-tag":"vd-image-tag"}
      env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
