apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: website
  namespace: flux-system
spec:
  targetNamespace: default
  chart:
    spec:
      chart: ./apps/website
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  interval: 5m
  values:
    registry: "ghcr.io/isaiahharvi"
    imagePullSecret: ghcr-registry
    services:
      website:
        name: website
        image: website
        tag: "0.0.1"
        containerPort: 6000
        servicePort: 80
    ingress:
      enabled: true
      host: isaiah.harville.dev
      annotations:
        kubernetes.io/ingress.class: nginx
      tls:
        - hosts:
            - isaiah.harville.dev
          secretName: harvilledev

