apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepo.yaml
  - helmrelease.yaml
  - issuer.yaml
  - ../../../secrets/cert-manager/cloudflare-api-token.yaml
namespace: cert-manager
