apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: vd-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Verus-Datum/app.git
  ref:
    branch: main
  secretRef:
    name: ghcr-registry
