apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Namespaces
  - ../../..//infrastructure/base/namespaces
  # Helm
  - ../../..//infrastructure/base/ingress-nginx
  - ../../..//infrastructure/base/cert-manager
  # - ../../..//infrastructure/base/metallb
  - ../../..//infrastructure/base/longhorn
  - ./secrets/cert-manager/cloudflare-api-token.yaml
