apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - patch-resources.yaml
  - patch-secure-ingress.yaml

configMapGenerator:
  - name: prod-config
    files:
      - app.env=prod.env
