apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion
spec:
  template:
    spec:
      containers:
      - name: orion
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vd
spec:
  template:
    spec:
      containers:
      - name: vd
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "150m"
            memory: "128Mi"
