registry: "ghcr.io/isaiahharvi/orion"
imagePullSecret: ghcr-registry

services:
  gui:
    name: gui
    image: "orion-gui"
    tag: "latest"
    containerPort: 5173
    servicePort: 80
    env:
      VITE_API_URL: "https://orion.harville.dev/api"

  api:
    name: api
    image: "orion-api"
    tag: "latest"
    containerPort: 5171
    servicePort: 80
    env:
      SERVICE: "api"
      SCAN_DIR: "/app/scans"
      KERAS_BACKEND: "torch"
      TORNET_ROOT: "data/TorNet"
      VITE_API_URL: "https://orion.harville.dev/api"

ingress:
  enabled: true
  host: orion.harville.dev
  annotations:
    kubernetes.io/ingress.class: nginx
  paths:
    - path: /
      serviceName: gui
      servicePort: 80
    - path: /api
      serviceName: api
      servicePort: 80
  tls:
    - hosts:
      - orion.harville.dev
      secretName: harvilledev
