apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "0.*"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - 192.168.1.240-192.168.1.250 # TODO: set to a free block on your LAN
