---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin-password: AgBri3PGBcEfwVjO62+wz+q+HM++rlD2UacF3WDs0AqegeFY7C1dcmTibEUd8RP4wBzPG/95nQ9p+4oHykkMoTvUwp5Rtw2mci75mEcwmbaZYDjOXKcOcnL4FVRbPxUcWDv29mRQG8gJVThw4o/C59PzZdrwt4iDgCeSH5+YzkVokTo5wDfOFPCoenF2yDvlgC9aNP+1QDz6zjnTB4mB0OzhwUEJRhCx43PyksKqsSfUf8EiiwWQHkGksrOWKSvDjHLNiyd8CypKOs3i8+Tbn5h8uHXQ37y/gO39D72wJWOkWuYTKrwMK/RXCNNCT6LcgqC159zKxVimJeWXiJAUc4t/L1TY5Yj0KmpaQKCQUsyeUKFOVtfGzoACZCt6otT4BYUH75JGC/bpLapJFpJlzQ2dlX4Hidi8p6N/AH7qoXYXo51QoPklkIE9KU1/XDgTOWGR2RtS0TVWB2khK/nFS0vNLdGEuHWzle7fCU0y+56TafxktRbetoK/ofAKCekTDHtBHE2urrX3WQ68Cy2bg1ejiHc4g+V+XaoRy79qKer6tARH1EQXaHS2enNfiNULb+biRg49pyVepgw0GC3jbspm/5GAgecI91hQ6P2/QeMPTB/Dye5GGw1BJFjvm489+L560CFQJbRJe0yjHXIp4SCUZ7TPvbjvq8B1ADb6i5dybHwKDM5HtIlNWILxi9mNbfvjWe8c8e0QDuiA
    admin-user: AgAf2fkrMBlzwvLSTPp0Usf+ryBDloGtlNRYlAyKk/nujqJeIRWkgMoNqW8FUsmM4dmL31xiwb6R18glrjuy02U9dPQqSPD/lDIqY3iA3OVDWhgRX8OM+cM4EeTLm/k2FMhNp0VRSA8gCD1wCrpGqI6azcZWT+DhPc6IyaRCJYnAWMexWkig/fmcNNrKR4L678O8gv2EsbCeL1RK8dbzsxm/EmNMQNU01OnDwtA9cjxf4nNem3X3Tn7M8Zo5/1tEcLlqWhg8/aNKqgdIspHS9ISMHZ/keMi/fdrRgj2AB4QHS2FC5gpR169cyrY7gFle4/oXQkiFQP+qqSpADgzD54BCg7U6pJrOzxZ3PNfN+Xrf/wbSuPw+D1gJF6gHs/ufrNuvMrztwmbDfzNGh+MGBMFe8HqG2OStGvoSViFSUHQAdA4NdpLl0TO83yehKFnpBmRzCDriHg/qXSyAsrJ6zvCTXASmD5YcFn68qYXRE/3o8W71BRA5X6pmFtRCYrxgZozFhGJbqqYvIugWayfwPP848p/zgdNYxn5l5UGlaZxvlc499Urfg18pxJDoYlTIWqDukgDo7UUtHZGSFWbPp6gKR+Bmd5OEKUmJz/PftLD8MWcC+Dx5vl3u6unkkDn0Xa4pykWuSUa1R4KWjHuGeOkUTwWJzlUKHq5NNTJKZNXsG7RqUpkXWYXnnxFYXJvWHeYjEZqW6A==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
