apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vd-db-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 10Gi

