{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "website.fullname" . }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "website.fullname" . }}
                port:
                  number: {{ .Values.services.website.servicePort }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}

