{{- $svc := .Values.services.website -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "website.fullname" . }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ $svc.servicePort }}
      targetPort: {{ $svc.containerPort }}
      protocol: TCP

