apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: orion
  namespace: flux-system
spec:
  checkout:
    gitRepositoryRef:
      name: flux-system
  update:
    path: "./flux-system"
    strategy: containers
  commit:
    author:
      name: flux-bot
      email: flux-bot@harville.dev
  push:
    branch: main

