apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: orion-gui
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: orion-gui
  policy:
    semver:
      range: ">=0.0.0"

