apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: orion
  namespace: apps
spec:
  interval: 30m
  chart:
    spec:
      chart: orion
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: TODO
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: orion-defaults
      valuesKey: values.yaml

