registry: "ghcr.io/isaiahharvi/website"
imagePullSecret: ghcr-registry

services:
  website:
    name: website
    image: "website"
    tag: "0.0.1"
    containerPort: 6000
    servicePort: 80

ingress:
  enabled: true
  host: isaiah.harville.dev
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    - hosts:
      - isaiah.harville.dev
      secretName: harvilledev

