apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: automation
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1m0s
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: flux-bot
        email: flux-bot@harville.dev
    push:
      branch: main
  update:
    strategy: SemVer
    semver:
      range: "*"
    path: "flux-system/overlay/helmreleases"
