apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: orion-gui
  namespace: flux-system
spec:
  interval: 1m
  image: ghcr.io/isaiahharvi/orion-gui
  secretRef:
    name: ghcr-registry
