apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: vd-gui
  namespace: flux-system
spec:
  image: ghcr.io/verus-datum/gui
  interval: 1m
  secretRef:
    name: ghcr-registry
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: vd-gui
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: vd-gui
  policy:
    alphabetical:
      order: asc
    # semver:
    #   range: ">=0.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: vd-api
  namespace: flux-system
spec:
  image: ghcr.io/verus-datum/api
  interval: 1m
  secretRef:
    name: ghcr-registry
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: vd-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: vd-api
  policy:
    alphabetical:
      order: asc
    # semver:
    #   range: ">=0.0.0"
