apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    prometheus:
      prometheusSpec:
        retention: 24h
        storageSpec: null
    alertmanager:
      alertmanagerSpec:
        storage: {}
    grafana:
      adminPassword: "admin"
      persistence:
        enabled: false
      service:
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        hosts:
          - grafana.harville.dev
        tls:
          - hosts:
              - grafana.harville.dev
            secretName: harville-wildcard-tls

