apiVersion: batch/v1
kind: CronJob
metadata:
  name: cf-ddns
  namespace: external-dns
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cf-ddns
          restartPolicy: OnFailure
          containers:
          - name: cf-ddns
            image: bitnami/kubectl:latest
            command:
              - /bin/sh
              - -c
              - |
                set -e
                IP=$(curl -fsS https://ifconfig.me)
                echo "Public IP is $IP"
                cat <<EOF > /tmp/record.json
                {
                  "type":"A",
                  "name":"*.harville.dev",
                  "content":"$IP",
                  "ttl":60,
                  "proxied":false
                }
                EOF
                curl -sX PATCH "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/dns_records/${CF_RECORD_ID}" \
                  -H "Authorization: Bearer ${CF_API_TOKEN}" \
                  -H "Content-Type: application/json" \
                  --data @/tmp/record.json \
                | jq .
            env:
              - name: CF_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: cf-ddns-secrets
                    key: CF_API_TOKEN
              - name: CF_ZONE_ID
                valueFrom:
                  secretKeyRef:
                    name: cf-ddns-secrets
                    key: CF_ZONE_ID
              - name: CF_RECORD_ID
                valueFrom:
                  secretKeyRef:
                    name: cf-ddns-secrets
                    key: CF_RECORD_ID

