---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: default
spec:
  encryptedData:
    admin-password: AgAZmDl6O+Nc9QaKLQdNndZLqooLf9OFUBs9TbAB4NsIBhRaKTqcSWemacgbff8M/ZywP8nS0+ZMml5JLuz7PVjoMXhEwb/AkXrm0+tqxoMkGoCg4ao4drL5OfbgYbPzpnnoFrwijBIpygSQvNJAXgLGEg8NjibgSfPm5ut5AePY0kUF5z8D+BJyJGLyhh8MmFHcPjKzIX3s6lYgCiGbzwwazd/uWY40RYbK71BBb6y2JfOVMNBikF/1HexF6quSz5hINTyBotuaPIOSVpJF+8/NFYx0VdR9gjyRPflIQHxEP/3IqQGA5XhudS046pUj/+q6zQ149wEJUZYmhhhSpUpxG6fPT7QHuFxLjeU/HxOR5+oDOEfZuoqnaBPz/hsteSs+AK/s7h9dAFdEjFHlC8NozizdGqsH3kX+uz201kkO2tnGEE8sIRrxRzNMnOGXsdOSUVjWdkNmBdBdi46hkCZgdjLgFwvaN6y1H1elgHWC1doElahMC7KdBFwGKT5D6BwGqWjnNcA1V4L63s29JqwxeqXTa5vlpR1oomPGH1FN1j7hGWd/oGiDm4JBLDID49U6/6WgPtyYHfqWCnrAOJsOtnKLh9eq7TabxQu4ZVMVYxMpkaLNcL0azQSPy1A9/KJRnXSnxF5xw5vOi1myrz9LZyr34CDKEEJsASiv+bxVcaP+7XG9lZAhMC4+Cl/t6JtjNuV9/aqmCQI=
    admin-user: AgCqTjS63l6KwjPpoaqICsa6B5jnnZK6uhotyUSgLvQgAIwTb4Id07ffl3SDz8xgLKrcoycUMayCfcaWd89h03geNew28RmPUOnmDKyh+ORDrFhx5w4RwZgvqCK+ioIacFCXQ5SIh7eb6QywNi1uoNgPPoYxwLiutyx7Z7guBmQ0088xMkpNkFPXeE3tdltrJu4MvitkBVhL6jorWZrTOh92ejdlnQ9toE6C2bSwrUDrNOoAHTN8y7kX/NGOYuLBwaGCIPT04VrXKqlzgmAbtL+cfFlP9lzwYg9OgR9FAolQwPESkB86Na6o7A2p2zYaPILmhgFE7Nd6xBr5oSlH9B9KjJxsdq/tFHNvaIrm3Sz5+t95uKzg3/usaSqxyFGiGtoDTo3d6GcSiVq+J7VC1ZkuoWRI6+ak59/pTyhmd3eZ61IWfVdLeTZ8JyfqiRXivSjnp/EhR91wcy2eQjMtG+8lf3E/1bC55GLn/ifWCf7N8Ux6jkmLcOC/bahfN5uq7pMOp72i+fjpH1jpV0wSdr2zItfA/kI3xodEJOOUS9Jd8ReDmBpUEP3TQnFTRFdWGYWR+Yl5wGQTRcoseRY8HlHz3px5On9KUD6IraRi7jVYdSvCD3E6EVAoUWpQHPxMg7Bu3EQX1seEKmKAKQEQ9W2K3cpBLRW3VAmLdfOtnzsVMH0fDdIwS53bifTVlVfn7qVvwzzllQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: default
