apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nginx-ingress-microk8s
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443

